=== public-transport/transport-api-endpoints/schema.json
{
  "$id": "https://raw.githubusercontent.com/public-transport/transport-apis/v1/schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "public transport API description",
  "type": "object",
  "required": [
    "name",
    "type",
    "supportedLanguages",
    "coverage",
    "options"
  ],
  "properties": {
    "name": {
      "type": "string"
    },
    "type": {
      "type": "object",
      "propertyNames": {
        "pattern": "^(efa|hafasMgate|hafasQuery|navitia|otpGraphQl|otpRest)$"
      },
      "additionalProperties": {
        "type": "boolean"
      }
    },
    "supportedLanguages": {
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^[a-z][a-z]$",
        "description": "ISO-639-1 language code"
      }
    },
    "coverage": {
      "type": "object",
      "minProperties": 1,
      "additionalProperties": false,
      "properties": {
        "realtimeCoverage": {
          "$ref": "#coverage"
        },
        "regularCoverage": {
          "$ref": "#coverage"
        },
        "anyCoverage": {
          "$ref": "#coverage"
        }
      }
    },
    "options": {
      "type": "object"
    }
  },
  "definitions": {
    "coverage": {
      "$id": "#coverage",
      "type": "object",
      "properties": {
        "area": {
      "type": "object"
        }
      }
    }
  }
}

=== public-transport/transport-api-endpoints/data/de/kvv-efa.json
{
    "name": "Karlsruher Verkehrsverbund (KVV)",
    "coverage": {
        "realtimeCoverage": {
            "area": {"type":"Polygon","coordinates":[[[8.06838,48.99943],[8.06665,49.01067],[8.07409,49.01726],[8.07358,49.02366],[8.07534,49.02744],[8.07423,49.03043],[8.0765,49.03327],[8.07212,49.04686],[8.06944,49.06274],[8.05686,49.06029],[8.05528,49.0672],[8.05585,49.07357],[8.07714,49.07202],[8.0795,49.07983],[8.0826,49.08157],[8.08496,49.08698],[8.09783,49.08788],[8.09911,49.08534],[8.10291,49.0858],[8.10259,49.09038],[8.10087,49.09102],[8.10159,49.09893],[8.11595,49.10014],[8.12081,49.10258],[8.11754,49.11852],[8.11832,49.13182],[8.1266,49.1306],[8.13407,49.1265],[8.15706,49.13123],[8.16579,49.13621],[8.16989,49.13617],[8.17056,49.13448],[8.16869,49.13403],[8.17152,49.12695],[8.17657,49.1256],[8.17633,49.12361],[8.179,49.12407],[8.1789,49.12154],[8.19153,49.11913],[8.198866,49.127993],[8.211751,49.126286],[8.21516,49.1177],[8.2226,49.11648],[8.22268,49.12015],[8.22433,49.12017],[8.22425,49.12729],[8.2274,49.12761],[8.23219,49.12411],[8.25553,49.12776],[8.25634,49.1248],[8.26385,49.12598],[8.26014,49.13476],[8.25966,49.13989],[8.26399,49.15327],[8.2622,49.16009],[8.25863,49.15904],[8.25651,49.17305],[8.24778,49.17163],[8.23391,49.17197],[8.22987,49.1697],[8.22839,49.17239],[8.21682,49.17102],[8.21496,49.1958],[8.21788,49.19611],[8.21656,49.20136],[8.21813,49.20192],[8.21597,49.20908],[8.22536,49.21186],[8.23707,49.21066],[8.23776,49.21257],[8.23627,49.21285],[8.23631,49.21674],[8.23808,49.21717],[8.23672,49.22547],[8.23806,49.23318],[8.23374,49.23635],[8.2332,49.24029],[8.23575,49.243],[8.23532,49.24982],[8.2316,49.25979],[8.25134,49.26323],[8.24766,49.27545],[8.28551,49.28219],[8.28596,49.28044],[8.29165,49.28091],[8.31665,49.29137],[8.31911,49.29326],[8.31742,49.29622],[8.32718,49.29765],[8.32928,49.29255],[8.34601,49.28879],[8.34565,49.28703],[8.34965,49.28769],[8.35393,49.28267],[8.35632,49.28354],[8.35817,49.28113],[8.36376,49.2838],[8.36658,49.28159],[8.36825,49.26884],[8.37543,49.26387],[8.37817,49.26511],[8.38201,49.26282],[8.38006,49.26198],[8.39221,49.25051],[8.39991,49.25353],[8.41161,49.25359],[8.41303,49.24973],[8.43769,49.26101],[8.46047,49.28048],[8.48089,49.2862],[8.48706,49.2902],[8.50417,49.2836],[8.51296,49.27853],[8.51984,49.27813],[8.52313,49.26834],[8.52603,49.26839],[8.52625,49.26569],[8.52877,49.26727],[8.54354,49.26283],[8.54804,49.26986],[8.57507,49.26222],[8.57048,49.25492],[8.61444,49.24215],[8.61443,49.2409],[8.62791,49.24312],[8.63481,49.241],[8.64269,49.23528],[8.64567,49.23985],[8.65223,49.2396],[8.65865,49.23754],[8.6593,49.23326],[8.66971,49.23284],[8.66946,49.23127],[8.68359,49.22832],[8.69458,49.23132],[8.70167,49.22624],[8.71454,49.23551],[8.72401,49.23754],[8.72813,49.22923],[8.73621,49.23011],[8.73405,49.22887],[8.74337,49.22487],[8.74988,49.21814],[8.74837,49.21774],[8.75181,49.20556],[8.77512,49.20183],[8.78333,49.19793],[8.79404,49.20072],[8.80079,49.1979],[8.81273,49.20093],[8.81521,49.20003],[8.81518,49.19616],[8.82392,49.19204],[8.82591,49.18845],[8.82348,49.1842],[8.82422,49.17926],[8.821,49.17862],[8.82407,49.17743],[8.8197,49.17504],[8.81883,49.17174],[8.81997,49.16846],[8.81669,49.16606],[8.81619,49.1614],[8.81792,49.15717],[8.82204,49.15605],[8.82476,49.16002],[8.83082,49.162],[8.8302,49.16047],[8.83281,49.15607],[8.84206,49.15025],[8.83555,49.14829],[8.83807,49.13993],[8.83077,49.13956],[8.82683,49.13288],[8.83123,49.12932],[8.82634,49.12668],[8.8291,49.12544],[8.8372,49.12689],[8.8593,49.12596],[8.86176,49.12976],[8.87117,49.13204],[8.87247,49.13118],[8.87181,49.12986],[8.8745,49.12874],[8.87331,49.12524],[8.87399,49.12354],[8.87634,49.12394],[8.87803,49.1187],[8.88137,49.11935],[8.88275,49.11741],[8.88742,49.11731],[8.88981,49.11502],[8.89151,49.10971],[8.89016,49.10894],[8.89053,49.10428],[8.89175,49.09967],[8.89422,49.09798],[8.89419,49.09561],[8.89028,49.0954],[8.89206,49.09456],[8.89183,49.09189],[8.8931,49.0912],[8.89322,49.085],[8.89039,49.08048],[8.88345,49.08094],[8.86776,49.07735],[8.87483,49.07554],[8.86484,49.07132],[8.87626,49.06959],[8.87932,49.0644],[8.8778,49.06175],[8.8797,49.06005],[8.87761,49.0585],[8.8672,49.0614],[8.83584,49.06157],[8.8421,49.05928],[8.83956,49.05669],[8.83968,49.05335],[8.83477,49.04985],[8.83379,49.0463],[8.83622,49.04509],[8.83593,49.04155],[8.83887,49.03806],[8.82734,49.03597],[8.82154,49.03749],[8.81205,49.0336],[8.80288,49.03648],[8.80174,49.0383],[8.80736,49.04026],[8.80345,49.04349],[8.79716,49.04552],[8.77903,49.04577],[8.77682,49.04204],[8.76902,49.04059],[8.77028,49.04223],[8.75959,49.04127],[8.76053,49.04625],[8.75924,49.04476],[8.75523,49.04524],[8.74457,49.03717],[8.7448,49.03319],[8.74315,49.03099],[8.73219,49.02681],[8.73253,49.0108],[8.7362,49.00794],[8.73871,49.00178],[8.73082,48.9971],[8.73534,48.99451],[8.72695,48.99316],[8.72504,48.99047],[8.71043,48.98906],[8.70704,48.99411],[8.70411,48.99368],[8.70106,48.99627],[8.68373,48.99235],[8.68235,48.99462],[8.67178,48.99365],[8.66803,48.99604],[8.66568,49.00187],[8.66062,49.00763],[8.65354,49.00325],[8.64751,49.00242],[8.64798,48.9898],[8.63987,48.98936],[8.62566,48.99351],[8.61348,48.99162],[8.60162,48.98553],[8.59594,48.98553],[8.58003,48.98986],[8.57438,48.98811],[8.57253,48.9854],[8.57284,48.98182],[8.5688,48.98011],[8.56895,48.97618],[8.56308,48.97471],[8.55736,48.97022],[8.56045,48.96729],[8.55831,48.96653],[8.55867,48.96092],[8.54925,48.95299],[8.54477,48.95509],[8.54242,48.95219],[8.53825,48.95366],[8.53633,48.94949],[8.53584,48.94423],[8.53971,48.94281],[8.53874,48.94021],[8.54329,48.93572],[8.54076,48.93218],[8.53443,48.92915],[8.53513,48.92686],[8.5539,48.92767],[8.55385,48.92021],[8.54318,48.91919],[8.5441,48.91817],[8.54192,48.91481],[8.54384,48.91395],[8.53403,48.90344],[8.53268,48.90516],[8.52457,48.90222],[8.52325,48.89969],[8.52051,48.90322],[8.51991,48.89994],[8.51801,48.89974],[8.51645,48.89492],[8.51778,48.88802],[8.51613,48.88747],[8.52246,48.88066],[8.52654,48.87999],[8.52127,48.87356],[8.51903,48.86747],[8.50612,48.85855],[8.49872,48.85737],[8.48818,48.8493],[8.47689,48.84822],[8.46805,48.84551],[8.47602,48.84014],[8.47386,48.83744],[8.47769,48.83083],[8.47557,48.82879],[8.48053,48.8278],[8.48102,48.82593],[8.49286,48.82013],[8.50039,48.81973],[8.50387,48.81698],[8.50486,48.8141],[8.5155,48.81372],[8.52411,48.81099],[8.53275,48.80407],[8.53067,48.80129],[8.51948,48.8006],[8.51662,48.79689],[8.52998,48.78494],[8.51501,48.7789],[8.5048,48.77751],[8.49797,48.77411],[8.49108,48.76385],[8.48618,48.76066],[8.48422,48.75689],[8.48522,48.7547],[8.48396,48.75044],[8.47943,48.74005],[8.47333,48.73519],[8.4748,48.73404],[8.47673,48.72506],[8.47183,48.71991],[8.45886,48.71785],[8.46057,48.7064],[8.46768,48.70021],[8.4594,48.69767],[8.44711,48.69952],[8.43964,48.69501],[8.44799,48.68721],[8.44528,48.6666],[8.44771,48.66333],[8.44384,48.65822],[8.43937,48.66112],[8.43135,48.66057],[8.43088,48.65876],[8.4353,48.65583],[8.43545,48.65099],[8.43167,48.64879],[8.43305,48.64801],[8.43008,48.6446],[8.41706,48.64684],[8.41447,48.64136],[8.40944,48.63951],[8.39324,48.63582],[8.38819,48.63699],[8.38839,48.62584],[8.38207,48.62268],[8.38201,48.61976],[8.3644,48.61514],[8.36339,48.61288],[8.36467,48.61099],[8.34889,48.60966],[8.35232,48.60405],[8.35795,48.60332],[8.35878,48.60102],[8.33536,48.59445],[8.32967,48.59145],[8.32325,48.59204],[8.31795,48.58825],[8.31536,48.58974],[8.31249,48.58837],[8.30895,48.58974],[8.30632,48.58828],[8.28497,48.58626],[8.27424,48.58907],[8.26115,48.58893],[8.2364,48.60172],[8.22192,48.60336],[8.23333,48.60641],[8.24638,48.60294],[8.24781,48.60879],[8.23274,48.61148],[8.23411,48.61612],[8.24008,48.6161],[8.2414,48.62937],[8.22927,48.63112],[8.22709,48.62732],[8.20764,48.62917],[8.19973,48.62843],[8.18064,48.64012],[8.17019,48.63822],[8.16184,48.64034],[8.16491,48.64545],[8.16131,48.64566],[8.15639,48.64935],[8.15291,48.64935],[8.14625,48.65345],[8.13821,48.65419],[8.14022,48.65629],[8.13621,48.65661],[8.12873,48.65404],[8.130136,48.651901],[8.1213,48.64903],[8.10751,48.65125],[8.10415,48.65569],[8.09339,48.65937],[8.08801,48.66359],[8.08386,48.66235],[8.0829,48.66613],[8.07307,48.67181],[8.07422,48.67373],[8.06714,48.67391],[8.06474,48.67109],[8.06158,48.67203],[8.06231,48.6746],[8.05689,48.67583],[8.05473,48.67468],[8.03352,48.67577],[8.03345,48.6784],[8.03754,48.67955],[8.03599,48.68255],[8.01959,48.6798],[8.01918,48.68709],[8.01369,48.6876],[8.01612,48.68271],[8.01407,48.68079],[8.00955,48.68494],[7.99185,48.68813],[7.98568,48.68817],[7.976654,48.683494],[7.974428,48.68602],[7.9735,48.69135],[7.97915,48.6974],[7.966062,48.70503],[7.963038,48.710594],[7.97254,48.71574],[7.95948,48.71849],[7.96709,48.72666],[7.96702,48.74577],[7.97067,48.75678],[7.97509,48.75951],[7.98374,48.76113],[7.99904,48.75881],[8.01308,48.7605],[8.02161,48.76659],[8.02603,48.78318],[8.03108,48.7878],[8.0426,48.79064],[8.05864,48.78887],[8.06655,48.79028],[8.07508,48.7938],[8.08851,48.80328],[8.10246,48.81792],[8.11013,48.84114],[8.12081,48.86379],[8.13059,48.8809],[8.14372,48.89905],[8.17615,48.93137],[8.19538,48.95551],[8.20129,48.95906],[8.23262,48.96654],[8.22439,48.9754],[8.21508,48.97504],[8.19997,48.96673],[8.19572,48.96911],[8.180651,48.966852],[8.18068,48.9783],[8.17068,48.97913],[8.16984,48.97641],[8.16005,48.97831],[8.15255,48.97704],[8.14084,48.97858],[8.13107,48.98294],[8.1275,48.98305],[8.12365,48.98582],[8.12011,48.98472],[8.11571,48.9867],[8.10827,48.98663],[8.10624,48.98884],[8.1006,48.98982],[8.08778,48.98969],[8.08525,48.99298],[8.07012,48.99611],[8.06838,48.99943]]]},
            "region": [
                "DE-BW"
            ]
        }
    },
    "options": {
        "endpoint": "https://projekte.kvv-efa.de/sl3/",
        "supportedOutputFormats": [ "XML", "JSON" ],
        "xmlOutputFormat": "full"
    },
    "supportedLanguages": [ "en", "de" ],
    "type": {
        "efa": true
    }
}

=== public-transport/transport-api-endpoints/data/de/gvh-efa.json
{
    "name": "Gro√üraum-Verkehr Hannover (GVH)",
    "coverage": {
        "realtimeCoverage": {
            "area": {"type":"Polygon","coordinates":[[[9.322671,52.406027],[9.314335,52.417756],[9.292568,52.416543],[9.283495,52.421775],[9.273693,52.420236],[9.259801,52.424207],[9.258173,52.428608],[9.280912,52.434005],[9.280282,52.440548],[9.267594,52.45126],[9.280311,52.458607],[9.270468,52.464897],[9.249891,52.464282],[9.239057,52.469837],[9.242541,52.476011],[9.257383,52.472848],[9.267352,52.476116],[9.260383,52.489125],[9.266358,52.490829],[9.261134,52.503593],[9.268741,52.507587],[9.25965,52.508738],[9.255726,52.517354],[9.248275,52.518081],[9.238688,52.529893],[9.276126,52.547239],[9.318086,52.555245],[9.340315,52.553924],[9.339311,52.557086],[9.347501,52.558716],[9.351426,52.555196],[9.369933,52.561706],[9.37266,52.569105],[9.346479,52.578889],[9.343129,52.581663],[9.345581,52.585384],[9.340716,52.586793],[9.346419,52.591213],[9.341646,52.592482],[9.342706,52.602374],[9.350119,52.601947],[9.354531,52.608213],[9.391018,52.611371],[9.390638,52.618116],[9.425558,52.617038],[9.438936,52.623557],[9.442112,52.632706],[9.454466,52.637732],[9.491447,52.63102],[9.494896,52.634825],[9.504757,52.626246],[9.522889,52.623056],[9.520189,52.62653],[9.531648,52.629852],[9.534981,52.634963],[9.53783,52.645097],[9.534142,52.66253],[9.542527,52.663279],[9.537737,52.665548],[9.539609,52.671415],[9.570348,52.676471],[9.591473,52.675487],[9.587593,52.673793],[9.585249,52.664541],[9.594403,52.663823],[9.589503,52.658226],[9.602836,52.654551],[9.599165,52.646744],[9.620249,52.645397],[9.62143,52.638905],[9.642156,52.633883],[9.634858,52.625494],[9.640262,52.622513],[9.646068,52.608299],[9.643375,52.606035],[9.65122,52.606924],[9.667573,52.600208],[9.698829,52.600105],[9.713611,52.61182],[9.705984,52.619738],[9.713365,52.623564],[9.711594,52.634082],[9.727388,52.633614],[9.734402,52.638093],[9.740185,52.631275],[9.768167,52.629426],[9.775596,52.622144],[9.793253,52.618907],[9.802043,52.614685],[9.800224,52.609775],[9.804535,52.606921],[9.835328,52.60533],[9.822969,52.600477],[9.830808,52.595497],[9.838034,52.597337],[9.847796,52.607911],[9.856133,52.603458],[9.888413,52.603349],[9.880249,52.596933],[9.876935,52.590716],[9.880686,52.589903],[9.907567,52.597391],[9.912503,52.592092],[9.944935,52.586912],[9.952883,52.587449],[9.951604,52.590959],[9.966219,52.590281],[9.969988,52.584957],[9.967125,52.578021],[9.979535,52.577164],[9.980461,52.581403],[9.984688,52.575204],[9.996578,52.576638],[9.989923,52.575393],[9.990569,52.571038],[9.985202,52.571825],[9.98214,52.567027],[9.984126,52.562036],[9.965072,52.553612],[9.966466,52.550206],[9.994856,52.544125],[9.98782,52.536206],[10.0217,52.536763],[10.03407,52.540474],[10.040774,52.535993],[10.059893,52.551806],[10.08115,52.555956],[10.090489,52.562022],[10.111972,52.554638],[10.126649,52.544904],[10.149119,52.538805],[10.141466,52.536977],[10.121203,52.509105],[10.134897,52.498875],[10.141507,52.498035],[10.15644,52.505129],[10.172,52.504249],[10.178606,52.513554],[10.199288,52.507534],[10.201199,52.509815],[10.223391,52.498606],[10.267403,52.488287],[10.271157,52.49374],[10.26764,52.501137],[10.272668,52.509477],[10.287503,52.506621],[10.278482,52.492856],[10.280384,52.489821],[10.271537,52.483526],[10.281499,52.474815],[10.289906,52.473265],[10.294999,52.46619],[10.293019,52.46362],[10.303234,52.45864],[10.299378,52.45568],[10.293703,52.461997],[10.288431,52.462001],[10.286516,52.458682],[10.289772,52.457798],[10.282623,52.453201],[10.294111,52.448613],[10.281599,52.44812],[10.25228,52.436174],[10.254683,52.423742],[10.250267,52.41977],[10.233453,52.427053],[10.20773,52.429155],[10.201955,52.426075],[10.197637,52.407086],[10.180759,52.39604],[10.166644,52.395231],[10.161043,52.399119],[10.130335,52.393928],[10.131293,52.383507],[10.142658,52.380909],[10.143938,52.369815],[10.156299,52.360844],[10.135784,52.357819],[10.136066,52.353645],[10.131122,52.352395],[10.125574,52.354632],[10.133278,52.350015],[10.136436,52.351978],[10.141131,52.351869],[10.13462,52.342969],[10.140329,52.339626],[10.125904,52.337823],[10.132425,52.328582],[10.126128,52.32806],[10.125566,52.322484],[10.118398,52.322143],[10.113465,52.300321],[10.070652,52.298367],[10.069876,52.304096],[10.06111,52.301485],[10.061206,52.294541],[10.039998,52.293716],[10.034127,52.291408],[10.034587,52.283702],[10.017615,52.279988],[9.996119,52.283563],[10.004599,52.290286],[10.006905,52.295409],[10.003444,52.29687],[9.998011,52.289979],[9.972207,52.293851],[9.971122,52.28553],[9.955754,52.286694],[9.951207,52.283673],[9.952007,52.274175],[9.948747,52.27507],[9.948599,52.282592],[9.912906,52.280658],[9.914137,52.267231],[9.90443,52.267527],[9.899811,52.2615],[9.876511,52.262531],[9.872338,52.270245],[9.84852,52.26565],[9.861104,52.255809],[9.860094,52.235569],[9.854217,52.239391],[9.84799,52.23807],[9.84375,52.230787],[9.84026,52.23213],[9.848524,52.242315],[9.848432,52.251256],[9.839458,52.262748],[9.832151,52.265729],[9.791036,52.251526],[9.790794,52.243239],[9.775755,52.239406],[9.776002,52.235014],[9.768918,52.231216],[9.782364,52.232828],[9.790437,52.228867],[9.789223,52.233667],[9.799679,52.2349],[9.80075,52.229703],[9.817214,52.228622],[9.814298,52.214756],[9.817915,52.212998],[9.803396,52.207054],[9.805505,52.20049],[9.802364,52.194709],[9.808036,52.192984],[9.807847,52.192152],[9.802771,52.193169],[9.802513,52.187909],[9.791502,52.190772],[9.792879,52.193096],[9.781782,52.190996],[9.784168,52.187904],[9.777335,52.178037],[9.784246,52.174465],[9.763595,52.170334],[9.762624,52.167312],[9.745139,52.16395],[9.726755,52.168501],[9.720122,52.158191],[9.692988,52.14492],[9.693638,52.135855],[9.67279,52.132489],[9.674697,52.129316],[9.671608,52.128058],[9.660589,52.132891],[9.628118,52.130693],[9.613526,52.13456],[9.613197,52.139097],[9.595921,52.144138],[9.556293,52.167226],[9.525572,52.159796],[9.504368,52.161016],[9.500235,52.168077],[9.496254,52.166683],[9.494244,52.17841],[9.504372,52.187338],[9.506745,52.197157],[9.491648,52.208628],[9.507506,52.204769],[9.516279,52.212187],[9.506853,52.213742],[9.503683,52.222601],[9.507382,52.221772],[9.497132,52.238779],[9.464351,52.255173],[9.455334,52.251637],[9.441537,52.253637],[9.43321,52.260336],[9.443823,52.274939],[9.423723,52.281104],[9.405169,52.299508],[9.396258,52.299027],[9.395208,52.305456],[9.404928,52.30409],[9.406267,52.311645],[9.389383,52.316372],[9.38963,52.321967],[9.363768,52.322576],[9.344728,52.333726],[9.328877,52.32833],[9.331753,52.33819],[9.327151,52.33893],[9.325585,52.353831],[9.322343,52.354205],[9.325041,52.36165],[9.320681,52.368762],[9.329157,52.370874],[9.321006,52.374763],[9.315553,52.384156],[9.315769,52.388186],[9.320354,52.388582],[9.317217,52.397215],[9.322671,52.406027]]]},
            "region": [ "DE-NI" ]
        }
    },
    "options": {
        "endpoint": "https://app.efa.de/mdv_server/app_gvh/",
        "supportedOutputFormats": [ "XML", "JSON" ],
        "xmlOutputFormat": "full"
    },
    "supportedLanguages": [ "de", "en" ],
    "type": {
        "efa": true
    }
}

=== public-transport/transport-api-endpoints/data/un/transitous.json
{
  "name": "Tansitous open public transport routing",
  "coverage": {
    "realtimeCoverage": {
      "region": [
        "BE",
        "CH",
        "NL"
      ]
    },
    "regularCoverage": {
      "region": [
        "DE",
        "DK",
        "EE",
        "GB",
        "IE",
        "LT",
        "LU",
        "LV",
        "NO",
        "PL",
        "SE"
      ]
    },
    "anyCoverage": {
      "region": [
        "AT",
        "AU-NSW",
        "CA",
        "ES",
        "FR",
        "IT",
        "US-CO",
        "US-IL",
        "US-MO",
        "US-OR"
      ]
    }
  },
  "options": {
    "endpoint": "https://routing.spline.de/api/",
    "intermodal": false,
    "motisVersion": "0.10.24",
    "supportedModes": []
  },
  "supportedLanguages": [],
  "type": {
    "motis": true
  }
}
